# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0069_shop_supplier_service_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetranslation',
            name='choices',
            field=models.CharField(default='', help_text='The attribute choices. Add all choices for String typed attributes.', max_length=256, verbose_name='choices'),
            preserve_default=False,
        ),
    ]
