# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_supplier', '0005_simple_supplier_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='stock_managed',
            field=models.BooleanField(default=False, help_text='Use this to override the supplier deafault stock behavior per product.', verbose_name='stock managed'),
        ),
    ]
